### ISSUE TITLE
Build stand-alone pathogenesis manuscript 

### ISSUE THREAD

**Issue by rando2** [greenelab/covid19-review#762]
**Is your feature request related to a problem? Please describe.**
Because we have split everything up, we will need to build docx versions of the manuscripts for submission. We're almost at that point with pathogenesis (#744).

**Describe the solution you'd like**
This will require a few pieces:
1. Select info from metadata.yaml depending on the unique author list for this manuscript
2. Generate a box defining all authors who belong to the consortium (how exactly do we want to phrase this?)
3. Render text from 07.pathogenesis.md only
4. Generate reference list from 07.pathogenesis.md text (see #732)

**Describe alternatives you've considered**
Some manual hijinks with docx involving a lot of copy and paste -- but that would not really work for the reference list.
Could also copy the text into a separate manubot project

**Additional context**

**Comment by agitter** [comment]
Because pathogenesis is being submitted first, I suggest we treat it as a special case.  If we get it to work, we can generalize to generate all of the individual manuscripts.  I'll make a pull request to get started.

We can add additional keys to each author in the metadata to help us select the named authors for each manuscript.  Then the front matter for each manuscript can select only those authors.  Imagine something like
```
authors:
  -
    name: Author A
    contributions:
      - Project Administration
      - Writing - Original Draft
      - Writing - Review & Editing
      - Methodology
    manuscripts:
      - pathogenesis
      - evolution
   -
    name: Author B
    contributions:
      - Writing - Original Draft
      - Writing - Review & Editing
    manuscripts:
      - pathogenesis
      - therapeutics
```

I'm leaving out most of the existing fields.  That assumes the contributions are the same for all manuscripts, which is not really true.  I'm also not yet sure how to order authors.  Maybe we need to manually list the order for each manuscript
```
authors:
  -
    name: Author A
    contributions:
      - Project Administration
      - Writing - Original Draft
      - Writing - Review & Editing
      - Methodology
    manuscripts:
      pathogenesis: 1
      evolution: 5
   -
    name: Author B
    contributions:
      - Writing - Original Draft
      - Writing - Review & Editing
    manuscripts:
      Pathogenesis: 3
      Therapeutics: 6
```

If we need to support manuscript-specific contributions, we could nest those too:
```
authors:
  -
    name: Author A
    pathogenesis:
      order: 1
      contributions:
        - Project Administration
        - Writing - Original Draft
        - Writing - Review & Editing
        - Methodology
    evolution:
      order: 5
      contributions:
        - Project Administration
        - Writing - Review & Editing
   -
    name: Author B
    pathogenesis:
      order: 3
      contributions:
      - Writing - Original Draft
      - Writing - Review & Editing
    therapeutics:
      order: 6
      contributions:
      - Writing - Original Draft
      - Writing - Review & Editing
```

For the box, we could create a new markdown file that is included in all of the individual manuscripts.  It could list all authors who are in the consortium.  It will require some trial and error but seems feasible.  Excluding named authors from the consortium list in the respective individual manuscripts would be harder.
